# Generated by Django 3.0.7 on 2020-06-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='created')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='custom_user.CustomUser', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordRestorationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='created')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='custom_user.CustomUser', verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
