# Generated by Django 3.0.7 on 2020-06-27 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text_materials', '0002_auto_20200627_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/', verbose_name='article image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='text_materials.Article', verbose_name='article')),
            ],
        ),
    ]
