# Generated by Django 3.0.7 on 2020-06-14 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('text', models.TextField(verbose_name='text')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_user.CustomUser', verbose_name='user')),
            ],
        ),
    ]
