# Generated by Django 3.0.7 on 2020-06-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_materials', '0002_auto_20200627_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important',
            field=models.BooleanField(default=False, verbose_name='important status'),
        ),
    ]
